### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by yooper** [DrSnowbird/netbeans#1]
In the readme, you reference **data_docker** as the mounting point for the workspace. In the actual code, it is **data-docker**

**Comment by DrSnowbird** [comment]
Hi Yooper,
Thanks so much for correcting the mistake in REAMDE.md.
It's been fixed and it is in autobuild in hub.docker.io now. 
Please give the autobuild about 15 minutes to complete its auto-rebuild.
v/r
   Ray
